language: node_js
node_js: node # latest
sudo: required
env:
  - FIXTURE=csharp,golang
  - FIXTURE=schema,swift,java
  - FIXTURE=elm,typescript
services:
  - docker
before_install:
  - docker pull dvdsgl/quicktype
install: >
  docker build \
    --cache-from dvdsgl/quicktype \
    --tag dvdsgl/quicktype .
script: >
  docker run \
    -e FIXTURE \
    -e CI \
    -e TRAVIS_BRANCH \
    -e TRAVIS_EVENT_TYPE \
    -e TRAVIS_PULL_REQUEST \
    -e CPUs=2 \
    dvdsgl/quicktype test/test
jobs:
  include:
    - stage: deploy
      env:
        - FIXTURE=none
      before_install: true
      install: npm install
      script: npm run pub
      before_deploy: cd output
      deploy:
        provider: npm
        email: djsiegel@gmail.com
        api_key:
          secure: "UgerPs+Y8yH1zHlyQ4LsKk6KUruJvaLPtlVpwTp19/U49q6be9YXut0C9NFtTguOxKMKdXQiQwcLYRnVcPFVqdnbFj6ie45pmJNNcq6xjfNbV+M26Y7FCzXGNrG2rspA5gCaXGLgbDegT1gpH0NC99V/WPvAlAiGxGhVmZuweNXt6HAhMyuWkKfBsxoUU8i3mUJr72UyO/DiJJxGK7kn4n3Z5jyaooaXOgweroVvbrg0/DFEz2ghQgWSIlNoER2OR9JNxhS0RRCmbtbGdpVlbQ3+NjOpBVjk0AXd8y/Jsr9re7ngqqYyH4zl7oo4SfijuErvznwMu0vwLiAd/c1MvNF+FI+EyvaQzipoulk9VMAXt5oAIXEBk0ZM8huhUcQ/ny3DSg7fqcUbgfh1XLAbdPvieWvYakOtixMBYJuPdH4xLMurcfTIaM+O7nKOONlcPsT5E9EE7D6NH3NKI/UDl78CkTAMIqyygV7ZqUO5x8QtuGsL2n33xoVikRdB8giVcitZTQmRKVKkDhGPfPJkunu8Rl2hgWCiC2/NwOmX2KLFozy4RN1R32zTnz0U3tzAhC33x3p2zvTttus75xRxqZ2DV1ArzpqxGFIiX0/Q2eeyn/cLRTPIWFhIGguYTDmyMPyp9XoJUUG83tzG4wGJx/EiZ9GhuSjLJEu3dbO9aiE="
        skip_cleanup: true
        on:
          branch: master
      cache:
        directories:
          - node_modules
          - bower_components
notifications:
  email:
    on_success: never # default: change
  slack:
    secure: "ZDnrCEPQn/8zfbegqdolW4oYuSj9VM7dN7EYSwwssRyTRzJN7S/F5XgPj9D4eA6TLCpdNQKXnlyflkWporkGZynANcsCBaSjOs5czPWkvVslOshVoECyvprgprYiRt7e7X/RY2sMP0ETPEDbWulXwH9FFSPyk8UeKcrtSVT42TFeHQLCWmRU+b+PwZsrpqJmxj+Gh3ycFWv4zigKRlmd7IUn62vkpg/cxlC+HT1cAEOfA4iZk4Qv/ck1g3OmWXygxVF7ICUGAus4Vp/VZ08F2xZko4aVtvw+v4jL6aRt6ol/HG5ag6SuZQTxIFCvoX2eDE3C+2xJc21liypxuJ1swUKUFKqrmiVyOl6Vly85QA+xtQBBNIyalUFn/RpumPOLSa1vnyN3KtPzam7ho9TCxnEZFysXk7jiBg2oGLMZ+acWR3rUcvHigX1edNcagM0V/G/Of4goW+R09miqeFG8UJyuD2TFOqDaeny2JzDBDebJGNuI+it7EE7uE1Rk+1xAeWIFFl8mUZ+smqeUz2mTZ/qfhYlGvGytcq3vUnhzytXxFYM94CtWAjJmGk5YLQAqyWltqtCH9WfGeyNMYBGOKFlZ/p/B5H0/KD4paeoSJ7oKUxVfDEQDz8Sgrs6IB0I6zV75mrV9YXmlDIPW4lYWot4ufG3LN0odUqhRDsbbt5o="
