language: node_js
node_js: 'node' # latest stable node release
env:
  - FIXTURE=csharp,golang
  - FIXTURE=java,schema,swift
  - FIXTURE=elm,typescript
jobs:
  include:
    - stage: deploy
      script:
        - npm run pub
        - cd output
      env:
        - FIXTURE=none
      deploy:
        provider: npm
        email: djsiegel@gmail.com
        api_key:
          secure: tYmFhDkXP+5QjWUkE7+ixF6S6yFynedzJQGWkZX0U6m4mFzOyp6XfjbOc2MGF0obQlZQpJ/agHIy8G3qFH8FsTNhMwybu1Uy8mQNnpm0KNJhgNabPLlyLNdG9KoBHHHntpD8212hKzy2KbOq9RTwyENLNIrq1GKiuQfAPGB5PY0BRKCz3aa740e6uXamkl/HG05ZVHoeKvW+PGjrNAZrRmoQfmjatkl88E4o0CrzY5NTDEB1/rGhKFxtIPQH3OieCTxXigzCWUiwia8XIyy44zNXjln9IKr8bLZjPTN6/s4xm6z/woqzY7ctqFXZ5SfIGLGnz16AJB36FCXFhPglggHJNlcCBIm+qUMkyIXA4EPZv7XNPV0vKXhoNdnxkKKafK+BfIrqobFw80ojIrUzW2+P8j+B4e8IrEK5sXv3alLzjld1JbzEyJj6YWVG8UrcJoVT1hz7y450Vb2j4MhGo0FxCh3CSjOXGAyibrM8BVLJ4gGCH7acQBm8W0Yk8X1knM3/bTlIRDu0g+CIV/IDIYlJ4d/1AW/ZWYja0BBz8EDjDAg/VICVk7yS+AYNkN6i+bZA7N6T12+LzTAJuYJjNN39smTHhnLotYYbI4WXmOa9O64E+Ps6NnQFoEpEqIpP3xyriu81ysE18pcZtoQkHuAwcbx/N7fb7k/0yJGCCsw=
        skip_cleanup: true
        on:
          repo: quicktype/quicktype
          branch: master  
addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main'
        key_url: 'https://apt-mo.trafficmanager.net/keys/microsoft.asc'
    packages:
      - dotnet-dev-1.0.1
      - maven
      - default-jdk
      - clang
before_install:
  - script/setup-ci.sh
install:
  - sysconfcpus/bin/sysconfcpus -n 2 npm install
script:
  - test/test
cache:
  directories:
    - bower_components
    - node_modules
    - output
    - $HOME/.cache/bower
    - $HOME/.nuget/packages
    - $HOME/swift
notifications:
  email:
    on_success: never # default: change
  slack:
    secure: IeuuD+F4GlTrrm/AFPk30PbRN6iYpq2SO9ta9C40UGtWWTR4bmxZUb5WftrRbt4dBtBb5+NrOBgEIIb5PhHvJP93k38OJgybBDoLzs163O4WQHivA9OztDGoWeE3SLSfRaaH+GSU3IzWRaNPbf9KFPsi5ydQdw3R9jv61w4EUKXmSsGuArOpGP2wFpKD0gamhkzjdYlsVWL/TDEVly1BYkT/8JcYqLKtgrKm8/7G5sT6utzdDAINofvooUyKlxBGx6sgWzKgvmSPPp9GWAp5UZq9rp9xsXf/l6h6gWsyTWrM+6jV94GdUQRgb8SxsrVWtDvKuNPuCJ3M8z1kb9hHY8aSQvZSxmCBm84bQkDT0ifkq+Ij9t1fsXOlMPSLAXjTGY39gLLL71eK/1NgmnchgzkifOjfFGC8/5m/yNGFmeA0nBxHtmGslkgJUHUUZkhkO2o31NQub2a7XfFmLzi9jO145kZU/5D/pQ2oncCs+MUdc5PyCiaVRgiG+v6EYw56+CTO/lgEYdjoOeuoTVQaZJmwwmZRQOczkLCQrv2i6wsq76OBrJBE/IarjPdnNobYLduovRocOSPHdOgoCes0ZG4PKi9jLLCNwCRYJAd0vunHDh7lipJmbq56JJiq6xMu8RvL228BSF51PRs8Wv0YipzSnLJQkjuHrmYUGyGlxGs=
